### ISSUE TITLE
Create custom section in right hand panel so custom properties can be added

### ISSUE THREAD

**Issue by mdonogma** [turbobabr/Sketch-Plugins-Cookbook#16]
I want to be able to create custom properties for any sketch object.

When object selected I should be able to update the custom properties. Example: integrationId, mycustom textfield, select custom value from dropdown for custom field.

There don’t seem to be any examples like this for sketchapp

**Comment by turbobabr** [comment]
I bet you could use new JS API for setting and getting meta data for any layer or document data. There's a special [Settings](https://developer.sketchapp.com/reference/api/#settings) section that does the job.

But I think you're looking for some sort of custom inspector solution which is out of the scope of this cookbook. It's possible to implement such thing but only via native `objective-c` plugin.

**Comment by mdonogma** [comment]
Would a layer or document setting persist with the file? Example : if field emailed to another user would the custom setting be accessible to that user via the plugin?

Question 2: does the export tool also export these custom settings so they can be accessed via the json output?
